server:
  port: 8083

spring:
  application:
    name: employeemanagement
  datasource:
    url: <url>
    username: <db_user>
    password: <db_pass>
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true