name: Deploy Spring Boot App to Proxmox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Spring Boot app
      run: mvn -B package --file pom.xml

    - name: Copy files to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        port: ${{ secrets.VM_PORT }}
        key: ${{ secrets.VM_PRIVATE_KEY_ARCHBOX }}
        source: "target/"
        target: "~/backend/"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Stop Previous Instance on Port 8083
      run: |
        echo ${{ secrets.SUDO_PASSWORD }} | sudo lsof -ti:8083 | xargs kill -9
    - name: Deploy to Proxmox
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        port: ${{ secrets.VM_PORT }}
        key: ${{ secrets.VM_PRIVATE_KEY_ARCHBOX }}
        script: |
          cd ~/backend
          # Replace 'app.jar' with your actual JAR file name
          mv target/employeemanagement-0.0.1-SNAPSHOT.jar app.jar
          nohup java -jar app.jar --spring.datasource.username=${{ secrets.DBUSER }} --spring.datasource.password=${{ secrets.DBPASS }} --spring.datasource.url=${{ secrets.DB_URL }} > deployment.log &