name: (Docker) Deploy Spring Boot App to Proxmox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot app
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t my-employee-app-be:latest .

      - name: Log in to Docker Hub (or other container registry)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker image to registry
        run: |
          docker tag my-employee-app-be:latest ${{ secrets.DOCKER_USERNAME }}/my-employee-app-be:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-employee-app-be:latest

  deploy:
    runs-on: ubuntu-latest


    needs: build

    steps:
      - name: Deploy to Proxmox
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_UBUNTU_SERVER_HOST }}
          username: ${{ secrets.VM_UBUNTU_SERVER_USERNAME }}
          port: ${{ secrets.VM_UBUNTU_SERVER_PORT }}
          key: ${{ secrets.VM_UBUNTU_SERVER_PRIVATE_KEY }}
          script: |
            mkdir -p ~/backend/logs
            cd ~/backend
            # Pull the latest Docker image from the container registry
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-employee-app-be:latest
            # Stop and remove the old container if running
            docker ps -q --filter "name=my-employee-app-be" | xargs -r docker stop | xargs -r docker rm
            # Run the new container
            docker run -d \
              -p 8083:8083
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_URL=${{ secrets.DB_URL }} \
              -v ~/backend/logs:/app/logs \
              --name my-employee-app-be \
              ${{ secrets.DOCKER_USERNAME }}/my-employee-app-be:latest
